# Generated by Django 5.0.3 on 2024-03-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air_Quality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('co2', models.FloatField()),
                ('tvoc', models.FloatField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
    ]
